### ISSUE TITLE
Needs help finding those NeoPixel LEDs

### ISSUE THREAD

**Issue by pandhersaab27** [BenjaminStienlet/ArduinoClock#1]
Hey Benjamin, 
I really liked the idea of using NeoPixel LEDs over the original project because of lot less clutter and also the cool color changing effect, can you please guide me where you got those NeoPixel LEDs because mostly they come in ring or as button LEDs but not as the standard ones.
Thank You in advance.

**Comment by BenjaminStienlet** [comment]
You can find the 5mm NeoPixel LEDs at Adafruit: [https://www.adafruit.com/product/1938](https://www.adafruit.com/product/1938)
I didn't buy these as they are quite expensive. Instead I bought similar LEDs on ebay. Search for "PL9823 F5 5mm".

**Comment by pandhersaab27** [comment]
Thank You very much for your prompt reply. I might need some additional help, on a tight deadline here.:)

**Comment by pandhersaab27** [comment]
Also can you please upload a copy of circuit diagram? or maybe some additional pictures? 
Thank you a lot really.
